export DISABLE_AUTO_TITLE='true'
export TERM="xterm-256color"
# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="af-magic"

plugins=(
  git
  zsh-autosuggestions
  docker
  virtualenv
  python
)

source $ZSH/oh-my-zsh.sh

bindkey -v vi
# bind key for auto completion
bindkey '^n' autosuggest-accept
FILE=/home/me/tmuxp_config.yaml
if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ] && test -f "$FILE"; then
  exec tmuxp load /home/me/tmuxp_config.yaml
fi
